### ISSUE TITLE
Config Implementation

### ISSUE THREAD

**Issue by Jaexyr** [trevorswan11/RemoveTheAnnoying#1]
Would love the option to still enable the Barber. Perhaps a config option

**Comment by trevorswan11** [comment]
> Would love the option to still enable the Barber. Perhaps a config option

You got it! Working on config options currently. New release probably in the next 12 hours.

**Comment by Jaexyr** [comment]
> > Would love the option to still enable the Barber. Perhaps a config option
> 
> You got it! Working on config options currently. New release probably in the next 12 hours.

Awesome! Thank you!

**Comment by trevorswan11** [comment]
The latest release (v1.1.0) now has config options along with a new feature. If you use Thunderstore, it might take a couple hours to get the release published, but its up on the github repo right now! Everything should be toggleable, but you probably need to relog into the game if you ever want to change something. Thanks for the suggestion!

**Comment by Jaexyr** [comment]
Thank you! I made my changes and haven't seen any maneater, but the mine still spawns, but that must be something dwelling in my other mods that could be conflicting. I appreciate you making your changes!

**Comment by trevorswan11** [comment]
Interesting. Ive observed the barber spawning in my testing, so it might just be a luck thing as the game spawns based on rarity. Im gonna be implementing some other things tonight, and will be sure to test the man-eater spawning config. What do you mean by "I made my changes and haven't seen any maneater, but the mine still spawns"? I haven't observed the mine spawning at all when disabled in the config (set to true)...

**Comment by Jaexyr** [comment]
I haven't seen the barber yet, but that was always a bit rare, unless I added ClaySurgeonOverhaul. But I didn't like the VentFix required for that.
I just meant I made my config changes in your mod. DisableBarber = False
I did just dig into LethalLevelLoader and found Mineshaft and set the moons to 0 though. Haven't tested it yet.

**Comment by trevorswan11** [comment]
are you saying that the mineshaft is still generating even with the config option set to true?

**Comment by Jaexyr** [comment]
Yes. But I must have something lurking in my list that's causing a conflict or overriding. There may be nothing wrong with your mod.

**Comment by trevorswan11** [comment]
Thanks for replying so promptly, I'll do some debugging tonight, but won't be doing anything that involves interactions with other mods as that would take a little too much of my time. I am interested to see the interaction between LethalLevelLoader and my mod, do you know what moon you saw a mineshaft on?

**Comment by Jaexyr** [comment]
I totally understand and don't blame you; The amount of mods I have is extensive. I'll let you know what I discover and what I've changed

**Comment by trevorswan11** [comment]
I've been testing and debugging the current state of the mod and have found that the maneater does spawn when the config is enabled, the barber does spawn when enabled, and mineshaft does spawn when enabled. I test my mod using imperium, and do not use any other gameplay/game mechanic mods during testing. Any issues you're encountering must be due to conflicts with other mods unfortunately :(
